# Generated by Django 2.0.9 on 2019-03-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp_database',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('otp_id', models.CharField(max_length=10)),
                ('otp_text', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
